# Start with keras:2.0
FROM shiying/keras:2.0

MAINTAINER Ying <s015348@aliyun.com>

# Add bash scripts for downloading source codes and data of project facial
COPY ./runTutorial.sh /runTutorial.sh
RUN chmod +x /runTutorial.sh

# Set default command
CMD /bin/bash

# Docker commands
#docker build -t shiying/facial:latest -f Dockerfile_facial .
#docker build --no-cache=true -t shiying/facial:latest -f Dockerfile_facial .
#docker login --username=shiying
#docker push shiying/facial:latest
#docker run -it --name=facial shiying/facial:latest bash
#docker rm -f $(docker ps -a -q)
#docker rm -f $(docker ps -a | grep none | awk '{print $1 }')
#docker images|grep none|awk '{print $3 }'|xargs docker rmi -f